#!/usr/bin/env bash
# Builds the v1.0.0 compatibility distribution from the canonical sources.
# Run from the repository root:  bash compat/build.sh
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
out="$root/v1.0.0"
mkdir -p "$out"

banner() {
  printf '/* %s\n   Generated by compat/build.sh — do not edit by hand.\n   Sources: %s */\n\n' "$1" "$2"
}

# --- tokens.css : current tokens + legacy aliases + .dark-mode parity -------
{
  banner "Harith Design System — v1.0.0 compatibility tokens." "tokens/*.css, compat/legacy-vars.css"
  for f in colors typography spacing radius elevation motion fonts status layers; do
    cat "$root/tokens/$f.css"; echo
  done
  cat "$root/compat/legacy-vars.css"; echo

  # v1.0.0 keyed dark mode on a .dark-mode class; the current system keys it on
  # :root[data-theme='dark']. Re-emit every dark block under the class form so
  # a page that only ever sets .dark-mode still gets the dark tokens.
  echo "/* .dark-mode parity — mirrors every :root[data-theme='dark'] block above. */"
  for f in colors typography spacing radius elevation motion fonts status layers; do
    awk "/^:root\[data-theme='dark'\]/ { print \":root.dark-mode, body.dark-mode {\"; inblock=1; next }
         inblock && /^}/ { print \"}\"; inblock=0; next }
         inblock { print }" "$root/tokens/$f.css"
  done

  # Follow the operating system when the page has made no explicit choice, so a
  # visitor in dark mode gets dark before any script runs — and a page that
  # offers a "system" setting can express it by removing the attribute.
  # Guarded against [data-theme='light'] so an explicit light choice still wins.
  echo "/* OS preference — applies unless the page has explicitly chosen light. */"
  echo "@media (prefers-color-scheme: dark) {"
  for f in colors typography spacing radius elevation motion fonts status layers; do
    awk "/^:root\[data-theme='dark'\]/ { print \"  :root:not([data-theme='light']) {\"; inblock=1; next }
         inblock && /^}/ { print \"  }\"; inblock=0; next }
         inblock { print \"  \" \$0 }" "$root/tokens/$f.css"
  done
  echo "}"
} > "$out/tokens.css"

# --- base.css --------------------------------------------------------------
{
  banner "Harith Design System — v1.0.0 compatibility base." "base.css"
  cat "$root/base.css"
} > "$out/base.css"

# --- components.css : the whole current surface + legacy shell aliases ------
{
  banner "Harith Design System — v1.0.0 compatibility components." "css/*.css, compat/legacy-shell.css"
  for f in shell core reading messaging; do
    cat "$root/css/$f.css"; echo
  done
  cat "$root/compat/legacy-shell.css"
} > "$out/components.css"

# --- utils.css : v1.0.0 utilities, unchanged --------------------------------
# They reference only legacy variable names, which legacy-vars.css supplies,
# so the original file works verbatim against the current tokens.
{
  banner "Harith Design System — v1.0.0 utilities." "compat/legacy-utils.css"
  cat "$root/compat/legacy-utils.css"
} > "$out/utils.css"

# --- scripts ---------------------------------------------------------------
cp "$root/compat/js/harith-store.js"   "$out/harith-store.js"
cp "$root/compat/js/theme-toggle.js"   "$out/theme-toggle.js"
cp "$root/compat/js/harith-shell.js"   "$out/harith-shell.js"
cp "$root/compat/js/widget-loader.js"  "$out/widget-loader.js"

echo "Built $out:"
ls -1 "$out" | sed 's/^/  /'
